apiVersion: v1
kind: BuildConfig
metadata:
  name: lsteck.java-spring-app-two.development
  labels:
    app: java-spring-app-two
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/lsteck/java-spring-app-two.git'
      ref: development
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: java2-sa
        - name: BRANCH
          value: development
